process.env.NODE_ENV ??= 'test'
process.env.ADMIN_USERNAME ??= 'admin'
process.env.ADMIN_PASSWORD ??= 'admin-e2e-pass'
process.env.ADMIN_EMAIL ??= 'admin@openapi.test'
process.env.SITE_URL ??= 'http://localhost:3000'

process.env.SMTP_HOST ??= '127.0.0.1'
process.env.SMTP_PORT ??= '2526'
process.env.SMTP_SECURE ??= 'false'
process.env.SMTP_FROM ??= 'no-reply@openapi.test'
process.env.SMTP_USER ??= ''
process.env.SMTP_PASS ??= ''
